[build-system]
requires = ["setuptools>=68"]
build-backend = "setuptools.build_meta"

[project]
name = "tr1363"
version = "0.1.0"
description = "TR1363 Battery Management System protocol"
readme = "README.md"
requires-python = ">=3.11"

authors = [
    {name="Cédric Félizard", email = "cedric@felizard.fr"}
]

license = {file="LICENSE"}

dependencies = [
    "pyserial",
    "paho-mqtt"
]

[tool.pytest.ini_options]
testpaths = ["tests"]
pythonpath = ["src"]
